services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "OwlBin@Dev123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/lib/mssql/data

volumes:
  sqlserver-data:

#接続文字列:Server=localhost,1433;Database=OwlBin;User Id=sa;Password=OwlBin@Dev123;TrustServerCertificate=True;
